parameters: {}
environment: {}
packages:
  - name: sample
    environment: {}
    parameters: {}
    actions:
      - name: random
        main: ''
        runtime: 'dotnet:default'
        environment: {}
        parameters: {}

